kind: Service
apiVersion: v1
metadata:
  name: search-service
spec:
  type: NodePort
  selector:
    app: search-service
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
  labels:
    app: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-servicee
        image: satyendrasingh/search:0.$BUILD_NUMBER
        ports:
        - containerPort: 8090
